// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/github/positoy/protobuf/proto/Person.proto

package io.github.positoy.protobuf.proto;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.positoy.protobuf.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
     * @return The enum numeric value on the wire for job.
     */
    int getJobValue();
    /**
     * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
     * @return The job.
     */
    io.github.positoy.protobuf.proto.PersonProto.Person.JobType getJob();

    /**
     * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
     * @return Whether the phones field is set.
     */
    boolean hasPhones();
    /**
     * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
     * @return The phones.
     */
    io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber getPhones();
    /**
     * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
     */
    io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder getPhonesOrBuilder();
  }
  /**
   * Protobuf type {@code io.github.positoy.protobuf.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.positoy.protobuf.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      email_ = "";
      job_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              job_ = rawValue;
              break;
            }
            case 42: {
              io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder subBuilder = null;
              if (phones_ != null) {
                subBuilder = phones_.toBuilder();
              }
              phones_ = input.readMessage(io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(phones_);
                phones_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.positoy.protobuf.proto.PersonProto.Person.class, io.github.positoy.protobuf.proto.PersonProto.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code io.github.positoy.protobuf.Person.JobType}
     */
    public enum JobType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Student = 0;</code>
       */
      Student(0),
      /**
       * <code>Developer = 1;</code>
       */
      Developer(1),
      /**
       * <code>Professor = 2;</code>
       */
      Professor(2),
      /**
       * <code>StockBroker = 3;</code>
       */
      StockBroker(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Student = 0;</code>
       */
      public static final int Student_VALUE = 0;
      /**
       * <code>Developer = 1;</code>
       */
      public static final int Developer_VALUE = 1;
      /**
       * <code>Professor = 2;</code>
       */
      public static final int Professor_VALUE = 2;
      /**
       * <code>StockBroker = 3;</code>
       */
      public static final int StockBroker_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static JobType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static JobType forNumber(int value) {
        switch (value) {
          case 0: return Student;
          case 1: return Developer;
          case 2: return Professor;
          case 3: return StockBroker;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<JobType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          JobType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<JobType>() {
              public JobType findValueByNumber(int number) {
                return JobType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.positoy.protobuf.proto.PersonProto.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final JobType[] VALUES = values();

      public static JobType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private JobType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.github.positoy.protobuf.Person.JobType)
    }

    /**
     * Protobuf enum {@code io.github.positoy.protobuf.Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.positoy.protobuf.proto.PersonProto.Person.getDescriptor().getEnumTypes().get(1);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.github.positoy.protobuf.Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.github.positoy.protobuf.Person.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
       * @return The type.
       */
      io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType getType();

      /**
       * <code>string number = 2;</code>
       * @return The number.
       */
      java.lang.String getNumber();
      /**
       * <code>string number = 2;</code>
       * @return The bytes for number.
       */
      com.google.protobuf.ByteString
          getNumberBytes();
    }
    /**
     * Protobuf type {@code io.github.positoy.protobuf.Person.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:io.github.positoy.protobuf.Person.PhoneNumber)
        PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PhoneNumber() {
        type_ = 0;
        number_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PhoneNumber();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                number_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.class, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder.class);
      }

      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType getType() {
        @SuppressWarnings("deprecation")
        io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType result = io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType.valueOf(type_);
        return result == null ? io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType.UNRECOGNIZED : result;
      }

      public static final int NUMBER_FIELD_NUMBER = 2;
      private volatile java.lang.Object number_;
      /**
       * <code>string number = 2;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        }
      }
      /**
       * <code>string number = 2;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (type_ != io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType.MOBILE.getNumber()) {
          output.writeEnum(1, type_);
        }
        if (!getNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, number_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (type_ != io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_);
        }
        if (!getNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, number_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber)) {
          return super.equals(obj);
        }
        io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber other = (io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber) obj;

        if (type_ != other.type_) return false;
        if (!getNumber()
            .equals(other.getNumber())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code io.github.positoy.protobuf.Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:io.github.positoy.protobuf.Person.PhoneNumber)
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_PhoneNumber_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.class, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder.class);
        }

        // Construct using io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          type_ = 0;

          number_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_PhoneNumber_descriptor;
        }

        @java.lang.Override
        public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber getDefaultInstanceForType() {
          return io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.getDefaultInstance();
        }

        @java.lang.Override
        public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber build() {
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber buildPartial() {
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber result = new io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber(this);
          result.type_ = type_;
          result.number_ = number_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber) {
            return mergeFrom((io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber other) {
          if (other == io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.getDefaultInstance()) return this;
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (!other.getNumber().isEmpty()) {
            number_ = other.number_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
         * @return The type.
         */
        @java.lang.Override
        public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType getType() {
          @SuppressWarnings("deprecation")
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType result = io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType.valueOf(type_);
          return result == null ? io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(io.github.positoy.protobuf.proto.PersonProto.Person.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.io.github.positoy.protobuf.Person.PhoneType type = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object number_ = "";
        /**
         * <code>string number = 2;</code>
         * @return The number.
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string number = 2;</code>
         * @return The bytes for number.
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string number = 2;</code>
         * @param value The number to set.
         * @return This builder for chaining.
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string number = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumber() {
          
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>string number = 2;</code>
         * @param value The bytes for number to set.
         * @return This builder for chaining.
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          number_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:io.github.positoy.protobuf.Person.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:io.github.positoy.protobuf.Person.PhoneNumber)
      private static final io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber();
      }

      public static io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PhoneNumber>
          PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
        @java.lang.Override
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOB_FIELD_NUMBER = 4;
    private int job_;
    /**
     * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
     * @return The enum numeric value on the wire for job.
     */
    @java.lang.Override public int getJobValue() {
      return job_;
    }
    /**
     * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
     * @return The job.
     */
    @java.lang.Override public io.github.positoy.protobuf.proto.PersonProto.Person.JobType getJob() {
      @SuppressWarnings("deprecation")
      io.github.positoy.protobuf.proto.PersonProto.Person.JobType result = io.github.positoy.protobuf.proto.PersonProto.Person.JobType.valueOf(job_);
      return result == null ? io.github.positoy.protobuf.proto.PersonProto.Person.JobType.UNRECOGNIZED : result;
    }

    public static final int PHONES_FIELD_NUMBER = 5;
    private io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber phones_;
    /**
     * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
     * @return Whether the phones field is set.
     */
    @java.lang.Override
    public boolean hasPhones() {
      return phones_ != null;
    }
    /**
     * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
     * @return The phones.
     */
    @java.lang.Override
    public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber getPhones() {
      return phones_ == null ? io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.getDefaultInstance() : phones_;
    }
    /**
     * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
     */
    @java.lang.Override
    public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder getPhonesOrBuilder() {
      return getPhones();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (job_ != io.github.positoy.protobuf.proto.PersonProto.Person.JobType.Student.getNumber()) {
        output.writeEnum(4, job_);
      }
      if (phones_ != null) {
        output.writeMessage(5, getPhones());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (job_ != io.github.positoy.protobuf.proto.PersonProto.Person.JobType.Student.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, job_);
      }
      if (phones_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPhones());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.positoy.protobuf.proto.PersonProto.Person)) {
        return super.equals(obj);
      }
      io.github.positoy.protobuf.proto.PersonProto.Person other = (io.github.positoy.protobuf.proto.PersonProto.Person) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (job_ != other.job_) return false;
      if (hasPhones() != other.hasPhones()) return false;
      if (hasPhones()) {
        if (!getPhones()
            .equals(other.getPhones())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + JOB_FIELD_NUMBER;
      hash = (53 * hash) + job_;
      if (hasPhones()) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhones().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.positoy.protobuf.proto.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.positoy.protobuf.proto.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.positoy.protobuf.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.positoy.protobuf.Person)
        io.github.positoy.protobuf.proto.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.positoy.protobuf.proto.PersonProto.Person.class, io.github.positoy.protobuf.proto.PersonProto.Person.Builder.class);
      }

      // Construct using io.github.positoy.protobuf.proto.PersonProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        job_ = 0;

        if (phonesBuilder_ == null) {
          phones_ = null;
        } else {
          phones_ = null;
          phonesBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.positoy.protobuf.proto.PersonProto.internal_static_io_github_positoy_protobuf_Person_descriptor;
      }

      @java.lang.Override
      public io.github.positoy.protobuf.proto.PersonProto.Person getDefaultInstanceForType() {
        return io.github.positoy.protobuf.proto.PersonProto.Person.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.positoy.protobuf.proto.PersonProto.Person build() {
        io.github.positoy.protobuf.proto.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.positoy.protobuf.proto.PersonProto.Person buildPartial() {
        io.github.positoy.protobuf.proto.PersonProto.Person result = new io.github.positoy.protobuf.proto.PersonProto.Person(this);
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        result.job_ = job_;
        if (phonesBuilder_ == null) {
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.positoy.protobuf.proto.PersonProto.Person) {
          return mergeFrom((io.github.positoy.protobuf.proto.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.positoy.protobuf.proto.PersonProto.Person other) {
        if (other == io.github.positoy.protobuf.proto.PersonProto.Person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.job_ != 0) {
          setJobValue(other.getJobValue());
        }
        if (other.hasPhones()) {
          mergePhones(other.getPhones());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.positoy.protobuf.proto.PersonProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.positoy.protobuf.proto.PersonProto.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private int job_ = 0;
      /**
       * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
       * @return The enum numeric value on the wire for job.
       */
      @java.lang.Override public int getJobValue() {
        return job_;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
       * @param value The enum numeric value on the wire for job to set.
       * @return This builder for chaining.
       */
      public Builder setJobValue(int value) {
        
        job_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
       * @return The job.
       */
      @java.lang.Override
      public io.github.positoy.protobuf.proto.PersonProto.Person.JobType getJob() {
        @SuppressWarnings("deprecation")
        io.github.positoy.protobuf.proto.PersonProto.Person.JobType result = io.github.positoy.protobuf.proto.PersonProto.Person.JobType.valueOf(job_);
        return result == null ? io.github.positoy.protobuf.proto.PersonProto.Person.JobType.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
       * @param value The job to set.
       * @return This builder for chaining.
       */
      public Builder setJob(io.github.positoy.protobuf.proto.PersonProto.Person.JobType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        job_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.JobType job = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearJob() {
        
        job_ = 0;
        onChanged();
        return this;
      }

      private io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber phones_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder> phonesBuilder_;
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       * @return Whether the phones field is set.
       */
      public boolean hasPhones() {
        return phonesBuilder_ != null || phones_ != null;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       * @return The phones.
       */
      public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber getPhones() {
        if (phonesBuilder_ == null) {
          return phones_ == null ? io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.getDefaultInstance() : phones_;
        } else {
          return phonesBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      public Builder setPhones(io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          phones_ = value;
          onChanged();
        } else {
          phonesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      public Builder setPhones(
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          phones_ = builderForValue.build();
          onChanged();
        } else {
          phonesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      public Builder mergePhones(io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (phones_ != null) {
            phones_ =
              io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.newBuilder(phones_).mergeFrom(value).buildPartial();
          } else {
            phones_ = value;
          }
          onChanged();
        } else {
          phonesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = null;
          onChanged();
        } else {
          phones_ = null;
          phonesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder getPhonesBuilder() {
        
        onChanged();
        return getPhonesFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      public io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder getPhonesOrBuilder() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilder();
        } else {
          return phones_ == null ?
              io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.getDefaultInstance() : phones_;
        }
      }
      /**
       * <code>.io.github.positoy.protobuf.Person.PhoneNumber phones = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder> 
          getPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumber.Builder, io.github.positoy.protobuf.proto.PersonProto.Person.PhoneNumberOrBuilder>(
                  getPhones(),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.positoy.protobuf.Person)
    }

    // @@protoc_insertion_point(class_scope:io.github.positoy.protobuf.Person)
    private static final io.github.positoy.protobuf.proto.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.positoy.protobuf.proto.PersonProto.Person();
    }

    public static io.github.positoy.protobuf.proto.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.positoy.protobuf.proto.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_positoy_protobuf_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_positoy_protobuf_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_positoy_protobuf_Person_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_positoy_protobuf_Person_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-io/github/positoy/protobuf/proto/Perso" +
      "n.proto\022\032io.github.positoy.protobuf\"\371\002\n\006" +
      "Person\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005emai" +
      "l\030\003 \001(\t\0227\n\003job\030\004 \001(\0162*.io.github.positoy" +
      ".protobuf.Person.JobType\022>\n\006phones\030\005 \001(\013" +
      "2..io.github.positoy.protobuf.Person.Pho" +
      "neNumber\032Y\n\013PhoneNumber\022:\n\004type\030\001 \001(\0162,." +
      "io.github.positoy.protobuf.Person.PhoneT" +
      "ype\022\016\n\006number\030\002 \001(\t\"E\n\007JobType\022\013\n\007Studen" +
      "t\020\000\022\r\n\tDeveloper\020\001\022\r\n\tProfessor\020\002\022\017\n\013Sto" +
      "ckBroker\020\003\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004H" +
      "OME\020\001\022\010\n\004WORK\020\002B/\n io.github.positoy.pro" +
      "tobuf.protoB\013PersonProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_positoy_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_positoy_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_positoy_protobuf_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Job", "Phones", });
    internal_static_io_github_positoy_protobuf_Person_PhoneNumber_descriptor =
      internal_static_io_github_positoy_protobuf_Person_descriptor.getNestedTypes().get(0);
    internal_static_io_github_positoy_protobuf_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_positoy_protobuf_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Type", "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
